[package]
name = "sing-box-windows"
version = "1.7.5"
description = "A Tauri App"
authors = ["XingGao"]
license = "MIT"
repository = "https://github.com/xinggaoya/sing-box-windows"
edition = "2021"
rust-version = "1.77.2"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
name = "app_lib"
crate-type = ["staticlib", "cdylib", "rlib"]

[build-dependencies]
tauri-build = { version = "2.0.1", features = [] }

[dependencies]
serde_json = "1.0"
# 日志
tracing = "0.1"
tracing-subscriber = { version = "0.3", features = ["env-filter", "json", "local-time"] }
tracing-appender = "0.2"
base64 = "0.13.0"
once_cell = "1.19.0"

tauri = { version = "2.0.6", features = ["tray-icon", "unstable"] }
tauri-plugin-log = "2.0.0-rc"
reqwest = { version = "0.12.9", features = ["json", "stream", "rustls-tls"] }
dirs = "5.0.1"
tokio = { version = "1.0", features = ["full"] }
futures = "0.3"
futures-util = "0.3"
tokio-tungstenite = { version = "0.18", features = ["rustls-tls-webpki-roots"] }
url = "2.3"
urlencoding = "2.1"
zip = { version = "0.5.13" }
lazy_static = "1.4.0"
winreg = "0.52.0"
winapi = { version = "0.3", features = ["wininet"] }
is_elevated = "0.1.2"
serde = { version = "1.0.214", features = ["derive"] }

[target.'cfg(not(any(target_os = "android", target_os = "ios")))'.dependencies]
tauri-plugin-autostart = "2"
tauri-plugin-positioner = "2.0.0-rc"
tauri-plugin-single-instance = "2.0.0-rc"
tauri-plugin-window-state = "2"
